
const bcrypt = require("bcryptjs");

const User = require("../Models/user");
const Student = require("../Models/student");
const Course = require("../Models/course");
const Branch = require("../Models/branch");
const {
  generateEnrollmentNumber,
} = require("../Utils/enrollmentGenerator");



const createStudent = async (req, res) => {
  try {
    const {
      name,
      email,
      password,
      phone,
      dateOfBirth,
      gender,
      course,
      branch,
      semester,
      section,
      admissionYear,
      address,
    } = req.body;

    if (
      !name ||
      !email ||
      !password ||
      !course ||
      !branch ||
      !semester ||
      !admissionYear
    ) {
      return res.status(400).json({
        success: false,
        message: "Required fields are missing",
      });
    }

  
    const normalizedEmail =
      email.trim().toLowerCase();

    const existingUser = await User.findOne({
      email: normalizedEmail,
    });

    if (existingUser) {
      return res.status(409).json({
        success: false,
        message: "Email already exists",
      });
    }

   
    const enrollmentNumber =
      await generateEnrollmentNumber({
        course,
        branch,
        admissionYear,
      });

   
    const hashedPassword =
      await bcrypt.hash(password, 10);

   
    const user = await User.create({
      name: name.trim(),
      email: normalizedEmail,
      password: hashedPassword,
      role: "student",
      phone,
      isActive: true,
    });

    try {
   
      const student = await Student.create({
        userId: user._id,

        // Generated by backend
        enrollmentNumber,

        dateOfBirth,
        gender,
        course: course.trim(),
        branch: branch.trim(),
        semester,
        section,
        admissionYear,
        address,
      });

    
      return res.status(201).json({
        success: true,
        message: "Student created successfully",

        student: {
          id: student._id,
          name: user.name,
          email: user.email,

          // Generated enrollment
          enrollmentNumber:
            student.enrollmentNumber,

          course: student.course,
          branch: student.branch,
          semester: student.semester,
          admissionYear:
            student.admissionYear,
        },
      });

    } catch (studentError) {
     
      await User.findByIdAndDelete(user._id);

      throw studentError;
    }

  } catch (error) {
    console.error(
      "Create Student Error:",
      error
    );

    // Unsupported branch
    if (
      error.message?.startsWith(
        "Unsupported branch:"
      )
    ) {
      return res.status(400).json({
        success: false,
        message: error.message,
      });
    }

    // Duplicate enrollment
    if (
      error.code === 11000 &&
      error.keyPattern?.enrollmentNumber
    ) {
      return res.status(409).json({
        success: false,
        message:
          "Generated enrollment number already exists. Please try again.",
      });
    }

    return res.status(500).json({
      success: false,
      message: "Failed to create student",
    });
  }
};


const getAllStudents = async (req, res) => {
  try {
    const [students, courses, branches] =
      await Promise.all([
        Student.find()
          .populate(
            "userId",
            "name email phone isActive"
          )
          .sort({
            createdAt: -1,
          }),

        Course.find()
          .select("_id courseCode courseName")
          .lean(),

        Branch.find()
          .select("_id branchCode branchName")
          .lean(),
      ]);

    const courseMap = new Map(
      courses.map((course) => [
        String(course._id),
        course.courseName,
      ])
    );

    const branchMap = new Map(
      branches.map((branch) => [
        String(branch._id),
        branch.branchName,
      ])
    );

    const formattedStudents =
      students.map((student) => {
        const studentObject =
          student.toObject();

        const courseId =
          String(student.course || "");

        const branchId =
          String(student.branch || "");

        return {
          ...studentObject,

          courseId:
            courseMap.has(courseId)
              ? courseId
              : null,

          branchId:
            branchMap.has(branchId)
              ? branchId
              : null,

          course:
            courseMap.get(courseId) ||
            student.course ||
            "Unknown Course",

          branch:
            branchMap.get(branchId) ||
            student.branch ||
            "Unknown Branch",
        };
      });

    return res.status(200).json({
      success: true,
      count: formattedStudents.length,
      students: formattedStudents,
    });
  } catch (error) {
    console.error(
      "Get Students Error:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Failed to fetch students",
    });
  }
};


const getStudentById = async (req, res) => {
  try {
    const { id } = req.params;

    const student =
      await Student.findById(id)
        .populate(
          "userId",
          "name email phone isActive"
        );

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }

    return res.status(200).json({
      success: true,
      student,
    });

  } catch (error) {
    console.error(
      "Get Student Error:",
      error
    );

    return res.status(500).json({
      success: false,
      message: "Failed to fetch student",
    });
  }
};



const updateStudent = async (req, res) => {
  try {
    const { id } = req.params;

    const {
      name,
      phone,
      dateOfBirth,
      gender,
      course,
      branch,
      semester,
      section,
      admissionYear,
      address,
    } = req.body;

 
    const student =
      await Student.findById(id);

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }

  
    student.dateOfBirth =
      dateOfBirth ??
      student.dateOfBirth;

    student.gender =
      gender ??
      student.gender;

    student.course =
      course ??
      student.course;

    student.branch =
      branch ??
      student.branch;

    student.semester =
      semester ??
      student.semester;

    student.section =
      section ??
      student.section;

    student.admissionYear =
      admissionYear ??
      student.admissionYear;

    student.address =
      address ??
      student.address;

    await student.save();

   
    const user =
      await User.findById(
        student.userId
      );

    if (user) {
      user.name =
        name ??
        user.name;

      user.phone =
        phone ??
        user.phone;

      await user.save();
    }

    return res.status(200).json({
      success: true,
      message:
        "Student updated successfully",

      student: {
        id: student._id,
        enrollmentNumber:
          student.enrollmentNumber,
        course: student.course,
        branch: student.branch,
        semester: student.semester,
        admissionYear:
          student.admissionYear,
      },
    });

  } catch (error) {
    console.error(
      "Update Student Error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Failed to update student",
    });
  }
};



const deleteStudent = async (req, res) => {
  try {
    const { id } = req.params;

    const student =
      await Student.findById(id);

    if (!student) {
      return res.status(404).json({
        success: false,
        message: "Student not found",
      });
    }


    await Student.findByIdAndDelete(id);


    await User.findByIdAndDelete(
      student.userId
    );

    return res.status(200).json({
      success: true,
      message:
        "Student deleted successfully",
    });

  } catch (error) {
    console.error(
      "Delete Student Error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Failed to delete student",
    });
  }
};

module.exports = {
  createStudent,
  getAllStudents,
  getStudentById,
  updateStudent,
  deleteStudent,
};